### ISSUE TITLE
我用最新的框架，在API调取Domain中出问题

### ISSUE THREAD

**Issue by XiaoHei880323** [phalapi/phalapi#77]
下载最新的框架后。什么都都没有修改，在src的api的user中调用domain层，但是提示没有找到
api层的代码如下：
        $domain = new \Domain_User();
        $userInfo = $domain->getUserInfo() ;
        print_r($userInfo) ;exit ;
在Domain层中，创建User.php文件类名:Domain_user，方法未getUserInfo().代码如下：
class Domain_User
{
    public function getUserInfo(){
        return [1,2] ;
    }
}

按照文档和案例来看，应该没有什么问题，但是提示就是找不到
<br />
<b>Fatal error</b>:  Uncaught Error: Class 'Domain_User' not found in D:\WWW\phalapi\src\app\Api\User.php:28
Stack trace:
#0 [internal function]: App\Api\User-&gt;login()
#1 D:\WWW\phalapi\vendor\phalapi\kernal\src\PhalApi.php(53): call_user_func(Array)
#2 D:\WWW\phalapi\public\index.php(9): PhalApi\PhalApi-&gt;response()
#3 {main}
  thrown in
<b>D:\WWW\phalapi\src\app\Api\User.php</b> on line
<b>28</b>
<br />

**Comment by phalapi** [comment]
类的文件名和类名没对应上，路径不对，可参考PSR-4：http://docs.phalapi.net/#/v2.0/autoload
